create table tipo_colaborador(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
descricao varchar2(50),
constraints pk_tipo_colaborador primary key (id),
constraints uk_descricao unique (descricao));

insert into tipo_colaborador(id,descricao)
values(null,'Estagiário');
commit;
insert into tipo_colaborador(id,descricao)
values(null,'Prestador de serviços');
commit;

create table raca(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
descricao varchar2(50),
constraints pk_raca primary key (id)
);

insert into raca(id,descricao)
values(null,'Branca');
commit;
insert into raca(id,descricao)
values(null,'Preta');
commit;
insert into raca(id,descricao)
values(null,'Parda');
commit;
insert into raca(id,descricao)
values(null,'Amarela');
commit;
insert into raca(id,descricao)
values(null,'Indígena');
commit;
insert into raca(id,descricao)
values(null,'Não informado');
commit;


create table estado_civil(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
descricao varchar2(50),
constraints pk_estado_civil primary key (id)
);

insert into estado_civil(id,descricao)
values(null,'Solteiro');
commit;
insert into estado_civil(id,descricao)
values(null,'Casado');
commit;
insert into estado_civil(id,descricao)
values(null,'Divorciado');
commit;
insert into estado_civil(id,descricao)
values(null,'Separado');
commit;
insert into estado_civil(id,descricao)
values(null,'Viúvo');
commit;

create sequence seq_grau_instrucao
start with 1
increment by 1
nocache;

create table grau_instrucao(
id varchar2(2) default rpad('0',2,seq_grau_instrucao.nextval),
descricao varchar2(50),
constraints pk_grau_instrucao primary key (id)
);
insert into grau_instrucao(descricao)
values('Analfabeto');
commit;
insert into grau_instrucao(descricao)
values('Até o 5º ano incompleto do ensino fundamental');
commit;

create table colaborador(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
cpf varchar2(11) not null,
nome varchar2(100) not null,
rg varchar2(11),
sexo varchar2(9),
id_raca number,
id_estado_civil number,
id_grau_instrucao varchar2(2),
nome_social varchar2(100),
data_nascimento date,
nacionalidade number,
naturalidade number,
id_ged varchar2(4000),
constraints pk_colaborador primary key (id),
constraints fk_raca foreign key(id_raca) references raca(id),
constraints fk_estado_civil foreign key(id_estado_civil) references estado_civil(id),
constraints fk_grau_instrucao foreign key(id_grau_instrucao) references grau_instrucao(id),
constraints ck_sexo check(sexo in('MASCULINO','FEMININO')),
constraints uk_cpf unique (cpf));

create table colaborador_tipo(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
id_colaborador number not null,
id_tipo_colaborador number not null,
ind_ativo char default 'S' not null,
constraints pk_colaborador_tipo primary key (id),
constraints fk_colaborador foreign key(id_colaborador) references colaborador(id),
constraints fk_tipo_colaborador foreign key(id_tipo_colaborador) references tipo_colaborador(id),
constraints uk_colaborador_tipo unique (id_colaborador,id_tipo_colaborador),
constraints ck_ind_ativo check(ind_ativo in('S','N')));

create table deficiencia(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
descricao varchar2(30) not null,
constraints pk_deficiencia primary key (id),
constraints uk_deficiencia unique (descricao));

insert into deficiencia(descricao)
values('Física');
commit;
insert into deficiencia(descricao)
values('Visual');
commit;
insert into deficiencia(descricao)
values('Auditiva');
commit;
insert into deficiencia(descricao)
values('Mental');
commit;
insert into deficiencia(descricao)
values('Intelectual');
commit;

--Saber o que fazer com indicador de reabilitação e o campo observação, se vai coloar na tb de especialização o generalização.

create table colaborador_deficiencia(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
id_colaborador_tipo number,
id_deficiencia number,
constraints pk_colaborador_deficiencia primary key(id),
constraints fk_colaborador_tipo foreign key(id_colaborador_tipo) references colaborador_tipo(id),
constraints fk_deficiencia foreign key(id_deficiencia) references deficiencia(id),
constraints uk_colaborador_deficiencia unique (id_colaborador_tipo,id_deficiencia))

create table colaborador_endereco(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
id_tipo_logradouro number,
logradouro varchar2(200),
numero varchar2(5) default 'S/N',
complemento varchar2(200),
bairro varchar2(100),
municipio varchar2(100),
uf varchar2(3),
cep varchar2(8),
id_colaborador_tipo number,
constraints pk_colaborador_endereco primary key(id),
constraints fk_colaborador_tipo_endereco foreign key(id_colaborador_tipo) references colaborador_tipo(id));

create table colaborador_telefone(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
ddd number,
numero number,
tipo varchar2(20),
id_colaborador_tipo number,
constraints pk_colaborador_telefone primary key(id),
constraints fk_colaborador_tipo_telefone foreign key(id_colaborador_tipo) references colaborador_tipo(id),
constraints uk_colaborador_telefone unique (id_colaborador_tipo,tipo));

create table colaborador_email(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
email varchar2(100),
tipo varchar2(20),
id_colaborador_tipo number,
constraints pk_colaborador_email primary key(id),
constraints fk_colaborador_tipo_email foreign key(id_colaborador_tipo) references colaborador_tipo(id),
constraints uk_colaborador_email unique (id_colaborador_tipo,tipo)
);

create table colaborador_residente_exterior(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
id_colaborador_tipo number,
pais varchar2(50),
logradouro varchar2(100),
numero varchar2(10) DEFAULT 'S/N',
complemento varchar2(100),
bairro varchar2(50),
cidade varchar2(50),
codigo_postal varchar2(10),
constraints pk_residente_exterior primary key(id),
constraints fk_colaborador_residente_ext foreign key(id_colaborador_tipo) references colaborador_tipo(id));

create table tempo_residencia(
id number,
descricao varchar2(100),
constraints pk_tempo_residencia primary key(id));

insert into tempo_residencia
values('1','Prazo Indeterminado');
commit;
insert into tempo_residencia
values('2','Prazo determinado');
commit;

create table class_trabalho_estrangeiro(
id number,
descricao varchar2(150),
constraints pk_class_trabalho_estrangeiro primary key(id));

insert into class_trabalho_estrangeiro
values('1','Refugiado');
commit;
insert into class_trabalho_estrangeiro
values('2','Solicitante de refúgio');
commit;
insert into class_trabalho_estrangeiro
values('3','Permanência no Brasil em razão de reunião familiar');
commit;
insert into class_trabalho_estrangeiro
values('4','Beneficiado pelo acordo entre países do Mercosul');
commit;
insert into class_trabalho_estrangeiro
values('5','Dependente de agente diplomático e/ou consultar de países que mantêm acordo de reciprocidade para o exercício de atividade remunerada no Brasil');
commit;
insert into class_trabalho_estrangeiro
values('6','Beneficiado pelo Tratado da Amizade, Cooperação entre a Reública Federativa do Brasil e a República Portuguesa');
commit;
insert into class_trabalho_estrangeiro
values('7','Outra Condição');
commit;

create table colaborador_imigrante(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
id_colaborador_tipo number,
id_tempo_residente number,
id_classificacao number,
constraints pk_colaborador_imigrante primary key(id),
constraints fk_colaborador_imigrante foreign key(id_colaborador_tipo) references colaborador_tipo(id),
constraints fk_tempo_residencia foreign key(id_tempo_residente) references tempo_residencia(id),
constraints fk_class_trab_estrangeiro foreign key(id_classificacao) references class_trabalho_estrangeiro(id));

create table unidade_pagamento(
id number,
descricao varchar2(20),
constraints pk_unidade_pagamento primary key(id));

insert into unidade_pagamento
values('1','Por Hora');
commit;
insert into unidade_pagamento
values('2','Por dia');
commit;
insert into unidade_pagamento
values('3','Por semana');
commit;
insert into unidade_pagamento
values('4','Por quinzena');
commit;
insert into unidade_pagamento
values('5','Por mês');
commit;
insert into unidade_pagamento
values('6','Por tarefa');
commit;
insert into unidade_pagamento
values('7','Não aplicável');
commit;


create table colaborador_remuneracao(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
id_colaborador_tipo number,
salario_base number,
id_unidade_pag number,
descricao varchar2(200),
constraints pk_colaborador_remuneracao primary key(id),
constraints fk_colaborador_remuneracao foreign key(id_colaborador_tipo) references colaborador_tipo(id),
constraints fk_id_unidade_pag foreign key(id_unidade_pag) references unidade_pagamento(id))


create table tipo_dependente(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY primary  key,
descricao varchar2(50))

---TABELA dependente

create table colaborador_tipo_dependente(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY ,
id_colaborador_tipo number,
id_dependente number,
id_tipo_dependente number,
ind_irrf char(1) default 'N',
ind_salario_familia char(1) default 'N',
ind_incapacidade char(1) default 'N',
constraints pk_colaborador_dependente primary key(id),
constraints fk_colaborador_tipo_dependente foreign key(id_colaborador_tipo) references colaborador_tipo(id),
constraints fk_tipo_dependente foreign key(id_tipo_dependente) references tipo_dependente(id),
constraints fk_dependente foreign key(id_dependente) references dependente(id),
constraints ck_ind_irrf check(ind_irrf in('S','N')),
constraints ck_ind_salario_familia check(ind_salario_familia in('S','N')),
constraints ck_ind_incapacidade check(ind_incapacidade in('S','N')));


create table motivo_afastamento(
id varchar2(3),
descricao varchar2(500) not null,
constraints pk_motivo_afastamento primary key(id));

insert into motivo_afastamento
values ('01','Acidente/Doença do trabalho');
insert into motivo_afastamento
values ('03','Acidente/Doença não relacionada ao trabalho');
insert into motivo_afastamento
values ('05','Afastamento/licença prevista em regime próprio (estatuto), sem remuneração');
insert into motivo_afastamento
values ('06','Aposentadoria por invalidez');
insert into motivo_afastamento
values ('07','Acompanhamento - Licença para acompanhamento de membro da família enfermo');
insert into motivo_afastamento
values ('08','Afastamento do empregado para participar de atividade do Conselho Curador do FGTS - art. 65, §6º, Dec.99.684/90 (Regulamento do FGTS)');
insert into motivo_afastamento
values ('10','Afastamento/licença prevista em regime próprio (estatuto), com remuneração');
insert into motivo_afastamento
values ('11','Cárcere');
insert into motivo_afastamento
values ('12','Cargo Eletivo - Candidato a cargo eletivo - Lei 7.664/1988. art. 25°, parágrafo único - Celetistas em geral');
insert into motivo_afastamento
values ('13','Cargo Eletivo - Candidato a cargo eletivo - Lei Complementar 64/1990. art. 1°, inciso II, alínea “l” - Servidor público, estatutário ou não, dos órgãos ou entidades da Administração Direta ou Indireta da União, dos Estados, do Distrito Federal, dos Municípios e dos Territórios, inclusive das fundações mantidas pelo Poder');
insert into motivo_afastamento
values ('14','Cessão / Requisição');
insert into motivo_afastamento
values ('15','Gozo de férias ou recesso - Afastamento temporário para o gozo de férias ou recesso');
insert into motivo_afastamento
values ('16','Licença remunerada - Lei, liberalidade da empresa ou Acordo/Convenção Coletiva de Trabalho');
insert into motivo_afastamento
values ('17','Licença Maternidade - 120 dias, inclusive para o cônjuge sobrevivente');
insert into motivo_afastamento
values ('18','Licença Maternidade - 121 dias a 180 dias, Lei 11.770/2008 (Empresa Cidadã), inclusive para o cônjuge');
insert into motivo_afastamento
values ('19','Licença Maternidade - Afastamento temporário por motivo de aborto não criminoso');
insert into motivo_afastamento
values ('20','Licença Maternidade - Afastamento temporário por motivo de licençamaternidade decorrente de adoção ou guarda judicial de criança, inclusive para o cônjuge sobrevivente');
insert into motivo_afastamento
values ('21','Licença não remunerada ou Sem Vencimento');
insert into motivo_afastamento
values ('22','Mandato Eleitoral - Afastamento temporário para o exercício de mandato eleitoral, sem remuneração');
insert into motivo_afastamento
values ('23','Mandato Eleitoral - Afastamento temporário para o exercício de mandato eleitoral, com remuneração');
insert into motivo_afastamento
values ('24','Mandato Sindical - Afastamento temporário para exercício de mandato sindical');
insert into motivo_afastamento
values ('25','Mulher vítima de violência - Lei 11.340/2006 - art. 9º §2o, II - Lei Maria da Penha');
insert into motivo_afastamento
values ('26','Participação de empregado no Conselho Nacional de Previdência Social-CNPS (art. 3º, Lei 8.213/1991)');
insert into motivo_afastamento
values ('27','Qualificação - Afastamento por suspensão do contrato de acordo com o art 476-A da CLT');
insert into motivo_afastamento
values ('28','Representante Sindical - Afastamento pelo tempo que se fizer necessário, quando, na qualidade de representante de entidade sindical, estiver participando de reunião oficial de organismo internacional do');
insert into motivo_afastamento
values ('29','Serviço Militar - Afastamento temporário para prestar serviço militar obrigatório');
insert into motivo_afastamento
values ('30','Suspensão disciplinar - CLT, art. 474');
insert into motivo_afastamento
values ('31','Servidor Público em Disponibilidade');
insert into motivo_afastamento
values ('33','Licença Maternidade - de 180 dias, Lei 13.301/2016');
insert into motivo_afastamento
values ('34','Inatividade do trabalhador avulso (portuário ou não portuário) por período superior a 90 dias');
insert into motivo_afastamento
values ('35','Licença Maternidade - Antecipação e/ou prorrogação mediante atestado médico');
commit;

create table colaborador_afastamento(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
id_colaborador_tipo number,
data_inicio date,
data_termino date,
observacao varchar2(1000),
constraints pk_colaborador_afastamento primary key(id),
constraints fk_colaborador_tp_afastamento foreign key(id_colaborador_tipo) references colaborador_tipo(id))


create table experiencia_profissional(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
id_colaborador number,
ano number,
empresa varchar2(150),
cargo varchar2(50),
constraints experiencia_profissional primary key(id),
constraints fk_colaborador_exp_prof foreign key(id_colaborador) references colaborador(id));

create table colaborador_curso_ext(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
id_colaborador number,
descricao varchar2(400),
constraints colaborador_curso_ext primary key(id),
constraints fk_colaborador_curso_ext foreign key(id_colaborador) references colaborador(id));

--tabela de natureza do estágio
create table natureza_estagio(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
sigla varchar2(1),
descricao varchar2(30),
constraints pk_natureza_estagio primary key(id),
constraints uk_sigla_natureza_estagio unique (sigla),
constraints uk_desc_natureza_estagio unique (descricao),
constraints ck_sigla_natureza_estagio check(sigla in('O','N'))
);

--tabela nivel do estágio
create table nivel_estagio(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
descricao varchar2(30),
constraints pk_nivel_estagio primary key(id),
constraints uk_descricao_nivel_estagio unique (descricao));

--tabela informações do estágio
create table colaborador_inf_estagio(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
id_colaborador_tipo number,
natureza number(1),
nivel number,
area_atuacao varchar2(60),
numero_apolice number,
data_prevista_termino date,
cpf_superior varchar2(11),
nome_superior varchar2(100),
id_setor number,
horario_inicio varchar2(8),
horario_final varchar2(8),
constraints pk_colaborador_inf_estagio primary key(id),
constraints fk_colab_tipo_inf_estagio foreign key(id_colaborador_tipo) references colaborador_tipo(id),
constraints fk_natureza_estagio foreign key(natureza) references natureza_estagio(id),
constraints fk_nivel_estagio foreign key(nivel) references nivel_estagio(id),
constraints fk_setor foreign key(id_setor) references setor(id));

create table estagio_inst_ensino(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
id_inf_estagio number,
cnpj varchar2(20),
razao_social varchar2(100),
cod_tip_logr number,
logradouro varchar2(100),
numero varchar2(5),
bairro varchar2(50),
cep varchar2(10),
cod_cid number,
sigla_uf varchar2(2),
complemento varchar2(100), 
constraints pk_estagio_inst_ensino primary key(id),
constraints fk_inf_estagio foreign key(id_inf_estagio) references colaborador_inf_estagio(id))

create table agente_integrador_estagio(
id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
id_inf_estagio number,
cnpj varchar2(20),
razao_social varchar2(100),
constraints pk_agente_integrador primary key(id),
constraints fk_agente_inf_estagio foreign key(id_inf_estagio) references colaborador_inf_estagio(id))
